#include <bits/stdc++.h>

using namespace std;

#define st first
#define nd second
#define pb push_back
#define cl(x,v) memset((x), (v), sizeof(x))
#define db(x) cerr << #x << " == " << x << endl
#define dbs(x) cerr << x << endl
#define _ << ", " <<

typedef long long ll;
typedef long double ld;
typedef pair<int,int> pii;
typedef pair<int, pii> piii;
typedef pair<ll,ll> pll;
typedef pair<ll, pll> plll;
typedef vector<int> vi;
typedef vector <vi> vii;

const ld EPS = 1e-9, PI = acos(-1.);
const ll LINF = 0x3f3f3f3f3f3f3f3f;
const int INF = 0x3f3f3f3f, MOD = 1e9+7;
const int N = 1e5+5;

typedef long long type;
//for big coordinates change to long long

bool ge(type x, type y) { return x + EPS > y; }
bool le(type x, type y) { return x - EPS < y; }
bool eq(type x, type y) { return ge(x, y) and le(x, y); }

struct point {
    type x, y;

    point() : x(0), y(0) {}
    point(type x, type y) : x(x), y(y) {}

    point operator -() { return point(-x, -y); }
    point operator +(point p) { return point(x + p.x, y + p.y); }
    point operator -(point p) { return point(x - p.x, y - p.y); }

    point operator *(type k) { return point(k*x, k*y); }
    point operator /(type k) { return point(x/k, y/k); }

    //inner product
    type operator *(point p) { return x*p.x + y*p.y; }
    //cross product
    type operator %(point p) { return x*p.y - y*p.x; }

    bool operator ==(const point &p) const{ return x == p.x and y == p.y; }
    bool operator !=(const point &p) const{ return x != p.x  or y != p.y; }
    bool operator <(const point &p) const { return (x < p.x) or (x == p.x and y < p.y); }

    // 0 => same direction
    // 1 => p is on the left 
    //-1 => p is on the right    
    int dir(point o, point p) {
        type x = (*this - o) % (p - o);
        return ge(x,0) - le(x,0);
    }

    bool on_seg(point p, point q) {
        if (this->dir(p, q)) return 0;
        return ge(x, min(p.x, q.x)) and le(x, max(p.x, q.x)) and ge(y, min(p.y, q.y)) and le(y, max(p.y, q.y));
    }

    ld abs() { return sqrt(x*x + y*y); }
    type abs2() { return x*x + y*y; }
    ld dist(point q) { return (*this - q).abs(); }
    type dist2(point q) { return (*this - q).abs2(); }

    ld arg() { return atan2l(y, x); }

    // Project point on vector y
    point project(point y) { return y * ((*this * y) / (y * y)); }

    // Project point on line generated by points x and y
    point project(point x, point y) { return x + (*this - x).project(y-x); }

    ld dist_line(point x, point y) { return dist(project(x, y)); }

    ld dist_seg(point x, point y) {
        return project(x, y).on_seg(x, y) ? dist_line(x, y) :  min(dist(x), dist(y));
    }

    point rotate(ld sin, ld cos) { return point(cos*x - sin*y, sin*x + cos*y); }
    point rotate(ld a) { return rotate(sin(a), cos(a)); }

    // rotate around the argument of vector p
    point rotate(point p) { return rotate(p.x / p.abs(), p.y / p.abs()); }

};

int direction(point o, point p, point q) { return p.dir(o, q); }

point rotate_ccw90(point p)   { return point(-p.y,p.x); }
point rotate_cw90(point p)    { return point(p.y,-p.x); }

//for reading purposes avoid using * and % operators, use the functions below:
type dot(point p, point q)     { return p.x*q.x + p.y*q.y; }
type cross(point p, point q)   { return p.x*q.y - p.y*q.x; }

//double area
type area_2(point a, point b, point c) { return cross(a,b) + cross(b,c) + cross(c,a); }

int angle_less(const point& a1, const point& b1, const point& a2, const point& b2) {
    //angle between (a1 and b1) vs angle between (a2 and b2)
    //1  : bigger
    //-1 : smaller
    //0  : equal
    point p1(dot(   a1, b1), abs(cross(   a1, b1)));
    point p2(dot(   a2, b2), abs(cross(   a2, b2)));
    if(cross(p1, p2) < 0) return 1;
    if(cross(p1, p2) > 0) return -1;
    return 0;
}

ostream &operator<<(ostream &os, const point &p) {
    os << "(" << p.x << "," << p.y << ")"; 
    return os;
}

vector<point> pts;

ll ternary_search(int l, int r){
    int lm = l, rm = r;
    while(r - l > 3) {
        int m1 = l + (r - l) / 3;
        int m2 = r - (r - l) / 3;
        ll f1 = abs(area_2(pts[lm], pts[m1], pts[rm]));     
        ll f2 = abs(area_2(pts[lm], pts[m2], pts[rm]));   
        if (f1 < f2) l = m1;
        else r = m2;
    }
    ll ans = 0;
    for(int i = l; i <= r; i++){
        ll aux = abs(area_2(pts[lm], pts[i], pts[rm]));
        ans = max(ans, aux);
    }
    return ans;
}

//Monotone chain O(nlog(n))
// #define REMOVE_REDUNDANT
#ifdef REMOVE_REDUNDANT
bool between(const point &a, const point &b, const point &c) {
    return (abs(area_2(a,b,c)) < EPS && (a.x-b.x)*(c.x-b.x) <= 0 && (a.y-b.y)*(c.y-b.y) <= 0);
}
#endif

void monotone_hull(vector<point> &pts) {
    sort(pts.begin(), pts.end());
    pts.erase(unique(pts.begin(), pts.end()), pts.end());
    vector<point> up, dn;
    for (int i = 0; i < pts.size(); i++) {
        while (up.size() > 1 && area_2(up[up.size()-2], up.back(), pts[i]) >= 0) up.pop_back();
        while (dn.size() > 1 && area_2(dn[dn.size()-2], dn.back(), pts[i]) <= 0) dn.pop_back();
        up.push_back(pts[i]);
        dn.push_back(pts[i]);
    }
    pts = dn;
    for (int i = (int) up.size() - 2; i >= 1; i--) pts.push_back(up[i]);

    #ifdef REMOVE_REDUNDANT
    if (pts.size() <= 2) return;
    dn.clear();
    dn.push_back(pts[0]);
    dn.push_back(pts[1]);
    for (int i = 2; i < pts.size(); i++) {
        if (between(dn[dn.size()-2], dn[dn.size()-1], pts[i])) dn.pop_back();
        dn.push_back(pts[i]);
    }
    if (dn.size() >= 3 && between(dn.back(), dn[0], dn[1])) {
        dn[0] = dn.back();
        dn.pop_back();
    }
    pts = dn;
    #endif
}

int main(){
    int n;
    cin >> n;
    pts.resize(n);
    vector<point> old(n);
    for(int i = 0; i < n; i++){
        cin >> pts[i].x >> pts[i].y;
        old[i] = pts[i];
    }
    monotone_hull(pts);
    n = pts.size();
    if(n < 3){
        cout << "0.0\n";
        return 0;
    }
    // db(n);
    if(n == 3){
        ll ans = 0;
        for(int i = 0; i < old.size(); i++){
            if(old[i].on_seg(pts[0], pts[1]) or old[i].on_seg(pts[1], pts[1]) or old[i].on_seg(pts[0], pts[2])) continue;
            ans = max(ans, abs(area_2(pts[0], pts[1], pts[2])) - abs(area_2(pts[0], pts[1], old[i])));
            ans = max(ans, abs(area_2(pts[0], pts[1], pts[2])) - abs(area_2(pts[2], pts[1], old[i])));
            ans = max(ans, abs(area_2(pts[0], pts[1], pts[2])) - abs(area_2(pts[0], pts[2], old[i])));
        }
        cout << ans/2;
        if(ans % 2) cout << ".5\n";
        else cout << ".0\n";
        return 0;
    }
    for(int i = 0; i < n; i++) pts.push_back(pts[i]);
    // ll ans = 0;
    // for(int l = 0; l < n; l++){
    //     for(int r = l + 2; r <= l + n - 2; r++){
    //         ll top_triangle = ternary_search(l, r);
    //         ll bot_triangle = ternary_search(r, l + n);
    //         ans = max(ans, top_triangle + bot_triangle);
    //     }
    // }
    ll ans = 0;
    for(int i = 0; i < n; i++){
        for(int l1 = i + 1, r = i + 2, l2 = r + 1; r < i + n - 1 and l1 < r and l2 < i + n; r++){
            ll top = abs(area_2(pts[i], pts[l1], pts[r]));
            while(l1 + 1 < r and abs(area_2(pts[i], pts[l1], pts[r])) <= abs(area_2(pts[i], pts[l1 + 1], pts[r]))){
                l1++;
                top = abs(area_2(pts[i], pts[l1], pts[r]));
            }

            ll bot = abs(area_2(pts[i], pts[l2], pts[r]));
            while(l2 + 1 < i + n and abs(area_2(pts[i], pts[l2], pts[r])) <= abs(area_2(pts[i], pts[l2 + 1], pts[r]))){
                l2++;
                bot = abs(area_2(pts[i], pts[l2], pts[r]));
            }
            // db(top _ bot);
            ans = max(ans, top + bot);
        }
    }
    cout << ans/2;
    if(ans % 2) cout << ".5\n";
    else cout << ".0\n";
    return 0;
}